const locations = [
  {
    region: "praha",
    regionCz: "Praha",
    districts: [
      "Praha 1",
      "Praha 2",
      "Praha 3",
      "Praha 4",
      "Praha 5",
      "Praha 6",
      "Praha 7",
      "Praha 8",
      "Praha 9",
      "Praha 10",
    ],
  },
  {
    region: "stredocesky",
    regionCz: "Středočeský",
    districts: [
      "Benešov",
      "Beroun",
      "Kolín",
      "Kladno",
      "Kutná Hora",
      "Mělník",
      "Mladá Boleslav",
      "Nymburk",
      "Praha-východ",
      "Praha-západ",
      "Příbram",
      "Rakovník",
    ],
  },
  {
    region: "plzensky",
    regionCz: "Plzeňský",
    districts: [
      "Domažlice",
      "Klatovy",
      "Plzeň-jih",
      "Plzeň-město",
      "Plzeň-sever",
      "Rokycany",
      "Tachov",
    ],
  },
  {
    region: "karlovarsky",
    regionCz: "Karlovarský",
    districts: ["Cheb", "Karlovy Vary", "Sokolov"],
  },
  {
    region: "ustecky",
    regionCz: "Ústecký",
    districts: [
      "Chomutov",
      "Děčín",
      "Litoměřice",
      "Louny",
      "Most",
      "Teplice",
      "Ústí nad labem",
    ],
  },
  {
    region: "liberecky",
    regionCz: "Liberecký",
    districts: ["Česká Lípa", "Jablonec nad Nisou", "Liberec", "Semily"],
  },
  {
    region: "kralovehradecky",
    regionCz: "Královéhradecký",
    districts: [
      "Hradec Králové",
      "Jičín",
      "Náchod",
      "Rychnov pod Kněžnou",
      "Trutnov",
    ],
  },
  {
    region: "pardubicky",
    regionCz: "Pardubický",
    districts: ["Chrudim", "Pardubice", "Svitavy", "Ústí nad Orlicí"],
  },
  {
    region: "vysocina",
    regionCz: "Vysočina",
    districts: [
      "Havlíčkův brod",
      "Jihlava",
      "Pelhřimov",
      "Třebíč",
      "Žďár nad Sázavou",
    ],
  },
  {
    region: "jihocesky",
    regionCz: "Jihočeský",
    districts: [
      "České Budějovice",
      "Český Krumlov",
      "Jindřichův Hradec",
      "Písek",
      "Prachatice",
      "Strakonice",
      "Tábor",
    ],
  },
  {
    region: "jihomoravsky",
    regionCz: "Jihomoravský",
    districts: [
      "Blansko",
      "Břeclav",
      "Brno-město",
      "Brno-venkov",
      "Hodonín",
      "Vyškov",
      "Znojmo",
    ],
  },
  {
    region: "olomoucky",
    regionCz: "Olomoucký",
    districts: ["Jeseník", "Olomouc", "Přerov", "Prostějov", "Šumperk"],
  },
  {
    region: "zlinsky",
    regionCz: "Zlínský",
    districts: ["Kroměříž", "Uherské Hradiště", "Vsetín", "Zlín"],
  },
  {
    region: "moravskoslezsky",
    regionCz: "Moravskoslezský",
    districts: [
      "Bruntál",
      "Frýdek-Místek",
      "Karviná",
      "Nový Jičín",
      "Opava",
      "Ostrava-město",
    ],
  },
];

export default locations;
